requested changes resolved
jstsanam/spotify-clone pull request #6
Opened 2024-12-03 04:20 UTC by jstsanam

Changes done:
- Changed inline styles in tailwind classes
- Adjusted footer to the bottom of the page
- Moved static files to a new directory named 'data'

2024-12-04 16:10 UTC, som-matrix requested changes
Please use tailwind default utility classes for height , width , background color , lineair graident in rest of the places

2024-12-04 16:10 UTC, som-matrix commented on src/App.tsx
> +      <main className="flex gap-2 h-[29rem]">
let's use the heights provided by tailwindcss -> https://tailwindcss.com/docs/height
if we need custom height later , we can add them to `tailwind.config.js` file, never do -> `h-[size]` it's a bad practice.

2024-12-04 16:10 UTC, som-matrix commented on src/components/Footer.tsx
> +    <div className="fixed inset-x-0 bottom-0 flex justify-between items-center m-2 pl-3 pr-3 pt-2 pb-2 bg-[linear-gradient(to_right,#ae2996,#825fc3,#519af4)]">
move this linear gradient to tailwind config file OR check if you can use default gradients provided by tailwind here -> https://tailwindcss.com/docs/background-image#linear-gradients

2024-12-04 16:10 UTC, som-matrix commented on src/components/Header.tsx
> +          className="p-2 rounded-full bg-[#1f1f1f]"
again custom background colors , move them to tailwind config file OR use default colors -> https://tailwindcss.com/docs/background-color

2024-12-04 16:10 UTC, som-matrix commented on src/components/main-panel/MainPanelFooter.tsx
> +import { footerData } from "../../data/footerData";
relative imports looks messy when there are nested folders , use absolute imports instead.
check how to use absolute imports in react i think you need to configure your `tsconfig.json` file.

relative imports -> `"../../data/footerData"`
absolute imports -> `"data/footerData"`

2024-12-04 16:10 UTC, som-matrix commented on src/components/main-panel/MainPanelCards.tsx
> +                }`}
use this package -> https://www.npmjs.com/package/clsx to handle dynamic classnames

2024-12-04 19:06 UTC, jstsanam commented on src/App.tsx
> +      <main className="flex gap-2 h-[29rem]">
Okay got it.

2024-12-04 19:08 UTC, jstsanam commented on src/components/main-panel/MainPanelFooter.tsx
> +import { footerData } from "../../data/footerData";
Okay, will have a look into it.

2024-12-15 04:31 UTC, som-matrix commented on tailwind.config.js
> +        'xxs': '0.5rem',
no this doesn't looks goods keep it `0.5: 0.5em` is better , please make this change in a followup PR

2024-12-15 04:32 UTC, som-matrix commented on src/components/Footer.tsx
> +}
add empty line below , make this change in a follow up PR

2024-12-15 04:32 UTC, som-matrix approved these changes
Added minor comments , please make the changes in a PR or you can directly push to main no issues

2024-12-15 04:32 UTC, merged